Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
  config.vm.define "XenServer" do |xen|
    config.vm.network "private_network", ip: "192.168.56.10", dns: "8.8.8.8"
    config.vm.hostname = "xenserver.example.com"
    config.vm.provider "libvirt" do |vm|
      vm.memory = 8192
      vm.cpus = 4
      vm.nested = true
      vm.cpu_model = "142"
    end
  end


end
